/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.output/server/wrangler.json --include-runtime=false bmz-ir-web/shared/types/worker-configuration.d.ts` (hash: a9204da801519003a5087e3881046aef)
interface __BaseEnv_Env {
	BLOB: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../../.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
