[package]
name = "bmz-audio"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
ffmpeg-next.workspace = true

bmz-core = { path = "../bmz-core" }
bmz-chart = { path = "../bmz-chart" }
bmz-ffmpeg = { path = "../bmz-ffmpeg" }

[target.'cfg(not(windows))'.dependencies]
cpal.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-audio = { version = "0.3", default-features = false, features = ["std", "AudioHardware", "objc2-core-audio-types"], optional = true }
objc2-core-audio-types = { version = "0.3", default-features = false, features = ["std", "CoreAudioBaseTypes"], optional = true }
objc2-core-foundation = { version = "0.3", default-features = false, features = ["std", "CFString"], optional = true }
mach2 = { version = "0.6", optional = true }

[target.'cfg(windows)'.dependencies]
cpal = { workspace = true, features = ["realtime"] }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_Media_KernelStreaming",
    "Win32_Media_Multimedia",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Threading",
    "Win32_System_Variant",
] }

[features]
default = []
asio = ["cpal/asio"]
pulseaudio = ["cpal/pulseaudio"]
pipewire = ["cpal/pipewire"]
experimental-coreaudio-ioproc = ["dep:objc2-core-audio", "dep:objc2-core-audio-types", "dep:objc2-core-foundation", "dep:mach2"]
