pub mod chart;
pub mod clear;
pub mod course;
pub mod ids;
pub mod input;
pub mod judge;
pub mod lane;
pub mod latency;
pub mod replay;
#[cfg(target_os = "macos")]
pub mod suspend;
#[cfg(target_os = "linux")]
#[path = "suspend_linux.rs"]
pub mod suspend;
pub mod time;
