[[textures]]
id = 1
path = "note.png"

[[textures]]
id = 2
path = "note-blue.png"

[[textures]]
id = 3
path = "note-red.png"

[play.note]
texture = 1
key_even_texture = 2
scratch_texture = 3
uv = { x = 0.0, y = 0.0, width = 1.0, height = 1.0 }
